/**
 * writer.mjs — the single writer of place identity.
 *
 * Takes the resolved config (from the prompt table, interactive or --answers;
 * both paths land here) and writes every adoption artifact:
 *
 *   place.config.ts                            regenerated in full
 *   knowledge/{Category}/ + knowledge/INBOX.md reseeded (demo content removed)
 *   CNAME                                      written for custom domains,
 *                                              removed for *.github.io
 *   CLAUDE.md                                  instance header block
 *   README.md                                  instance repo front page
 *   FRAMEWORK-VERSION                          framework version at init time
 *   scripts/ci/genericity-denylist.local.txt   adopter place-name terms
 *   .sekai-template                            removed (template → instance)
 *
 * Writing is a pure function of the resolved config, with no timestamps or
 * environment reads, so the same answers always produce byte-identical output.
 */

import {
  existsSync,
  mkdirSync,
  readFileSync,
  rmSync,
  unlinkSync,
  writeFileSync,
} from 'node:fs';
import { join } from 'node:path';

/* ── TypeScript-literal serializer (deterministic, repo code style) ──────── */

function tsString(s) {
  // \r and U+2028/U+2029 are (parser-vintage) line terminators: raw, they
  // would truncate the single-quoted literal and break place.config.ts at the
  // next build, far from the cause. Answers JSON can carry them; readline
  // cannot.
  return `'${s
    .replace(/\\/g, '\\\\')
    .replace(/'/g, "\\'")
    .replace(/\n/g, '\\n')
    .replace(/\r/g, '\\r')
    .replace(/\u2028/g, '\\u2028')
    .replace(/\u2029/g, '\\u2029')}'`;
}

const BARE_KEY_RE = /^[A-Za-z_$][A-Za-z0-9_$]*$/;

function tsValue(v, indent) {
  const pad = '  '.repeat(indent);
  const padIn = '  '.repeat(indent + 1);
  if (typeof v === 'string') return tsString(v);
  if (typeof v === 'number' || typeof v === 'boolean') return String(v);
  if (Array.isArray(v)) {
    if (v.length === 0) return '[]';
    if (v.every((x) => typeof x !== 'object')) {
      const inline = `[${v.map((x) => tsValue(x, 0)).join(', ')}]`;
      if (inline.length <= 72) return inline;
    }
    const items = v.map((x) => `${padIn}${tsValue(x, indent + 1)},`).join('\n');
    return `[\n${items}\n${pad}]`;
  }
  const entries = Object.entries(v).filter(([, val]) => val !== undefined);
  if (entries.length === 0) return '{}';
  const body = entries
    .map(
      ([k, val]) =>
        `${padIn}${BARE_KEY_RE.test(k) ? k : tsString(k)}: ${tsValue(val, indent + 1)},`,
    )
    .join('\n');
  return `{\n${body}\n${pad}}`;
}

/* ── place.config.ts template ────────────────────────────────────────────── */

const CONFIG_HEADER = `/**
 * place.config.ts — THE ingress for this instance's place identity.
 *
 * Everything place-specific (name, categories, map, feature toggles, SEO) lives
 * here. \`src/\` and \`scripts/\` stay generic and read from this file, so a single
 * file re-places the whole site. Generated by \`npm run init\` — the single
 * writer of this file. Edit values by hand freely after init; re-running the
 * wizard regenerates it (and reseeds knowledge/ with empty category folders).
 *
 * The \`home\` block ships generic defaults: no wizard prompt walks the home-page
 * copy. Replace it with place-specific copy by hand, or let the /adopt skill
 * draft it behind human approval.
 */
`;

const CONFIG_INTERFACE = `
export interface PlaceConfig {
  place: {
    name: string;
    tagline: string;
    domain: string;
    locale: string;
    languages: string[];
  };
  /** 5-14 categories. slug/icon/description feed nav, hubs, and category pages. */
  categories: Array<{
    slug: string;
    title: string;
    icon: string;
    description: string;
  }>;
  /** Leaflet init: center [lat, lng], zoom, and maxBounds [[S,W],[N,E]]. */
  map: {
    center: [number, number];
    zoom: number;
    maxBounds: [[number, number], [number, number]];
  };
  features: {
    graph: boolean;
    map: boolean;
    dashboard: boolean;
    soundscape: boolean;
    feedback: boolean;
    chat: boolean;
    social: boolean;
    analytics: boolean;
  };
  /**
   * Outbound identity links. \`repo\` + \`email\` are always rendered (footer,
   * SEO sameAs/contactPoint, the "edit on GitHub" affordance). \`social\`
   * handles feed the footer social row and SEO sameAs, and render ONLY when
   * \`features.social\` is true. Handles include the leading \`@\`; component
   * code strips it when building platform URLs.
   */
  links: {
    repo: string;
    email: string;
    social: {
      twitter?: string;
      threads?: string;
      instagram?: string;
    };
  };
  seo: {
    defaultOgImage: string;
    twitterHandle?: string;
  };
  home: {
    hero: {
      subtitle: string;
      description: string;
      highlight: string;
      cta: { explore: string; github: string };
    };
    stats: Array<{ icon: string; number: string; label: string }>;
    doors: Array<{
      icon: string;
      href: string;
      title: string;
      sub: string;
      tone: 'green' | 'blue' | 'amber' | 'plum';
    }>;
    coverStory: {
      heading: string;
      lead: string;
      quotes: Array<{
        era: string;
        quote: string;
        cite: string;
      }>;
      closing: string[];
      aboutLinkText: string;
    };
    randomDiscovery: {
      button: string;
      subtitle: string;
      description: string;
    };
    features: {
      title: string;
      cards: Array<{ icon: string; title: string; description: string }>;
      cta: { graph: string; ssot: string };
    };
    exhibitions: {
      heading: string;
      divider: string;
      halls: Array<{
        label: string;
        paragraphs: Array<{
          text: string;
          pillHref: string;
          pillIcon: string;
          pillLabel: string;
          categorySlug: string;
        }>;
      }>;
    };
    recentUpdates: {
      heading: string;
      subtitle: string;
      viewAll: string;
      latestLabel: string;
    };
    contribute: {
      heading: string;
      description: string;
      guideLabel: string;
      githubLabel: string;
    };
  };
}
`;

export function renderPlaceConfig(cfg) {
  return `${CONFIG_HEADER}${CONFIG_INTERFACE}
const config: PlaceConfig = ${tsValue(cfg, 0)};

export default config;
`;
}

/* ── Seeded file contents ────────────────────────────────────────────────── */

const INBOX_MD = `# Article Proposals

Queue for proposed articles. Add ideas here; move to the appropriate category directory when written.

## Format

- **Title**: Working title
- **Category**: Which category
- **Angle**: Perspective or hook
- **Sources**: At least one source URL or reference
- **Priority**: High / Medium / Low

---

## Proposals

(none yet)
`;

function renderClaudeMd(cfg) {
  const { name, tagline, domain } = cfg.place;
  return `# ${name}

Knowledge base for **${name}** (${domain}), built on the
[sekai-kb](https://github.com/wilsonkichoi/sekai-kb) framework. ${tagline}

> This file is **instance-owned** (\`merge=ours\` in \`.gitattributes\`): framework
> upgrades never overwrite it. Edit it freely to describe your instance.

## Where things live

- **Place identity (the one file to edit):** \`place.config.ts\` — name, tagline,
  domain, categories, map, feature toggles, links, and home-page copy.
- **Content (single source of truth):** \`knowledge/{Category}/*.md\` — plain Markdown.
  Everything the site renders is derived from this at build time.
- **Media:** \`public/media/\` and other \`public/\` assets.
- **Architecture diagrams (engineering SSOT):** \`docs/diagrams/*.drawio\`.

## How the site builds

\`knowledge/\` → \`sync.sh\` → parallel prebuild (kb-index, search, content-dates,
git-info, related, changelog, map-markers, dashboard-lite) → \`astro build\` →
post-build contract checks. \`src/content/\` and \`src/data/\` are derived, gitignored
projections of \`knowledge/\` — never edit them directly.

## Iron rules

1. **SSOT:** \`knowledge/\` is the only content source of truth; \`src/content/\` is
   derived (gitignored, written by sync) and never edited directly.
2. **Genericity + English-only:** zero place-specific strings and zero CJK/multi-language
   code paths in any code tree — \`src/\`, \`scripts/\`, \`tests/\`, future \`workers/\`/plugin
   code; test fixtures are code. Place identity flows only from \`place.config.ts\` +
   \`knowledge/\` + \`public/media/\`. Machine-gated by \`npm run genericity\`
   (\`scripts/ci/check-genericity.sh\` + \`scripts/ci/check-english-only.mjs\`).
3. **Framework vs instance:** \`src/\` and \`scripts/\` are framework-owned — customize
   through config, content, and media. Anything more is upstreamed to sekai-kb and
   pulled back as a tagged release. The genericity gate is the structural guarantee.
`;
}

/**
 * The instance repo front page. Rendered from config only (place name, tagline,
 * domain) so the same answers always produce byte-identical output — like
 * renderClaudeMd, no timestamps or environment reads. Overwrites the template's
 * own README on adoption; instance-owned (merge=ours) so upgrades never clobber it.
 */
function renderReadme(cfg) {
  const { name, tagline, domain } = cfg.place;
  const url = `https://${domain}`;
  return `# ${name}

${tagline}

Knowledge base for **${name}**, published at [${domain}](${url}). Built on the
[sekai-kb](https://github.com/wilsonkichoi/sekai-kb) framework: plain Markdown
content under \`knowledge/\` rendered as a fast, AI-native static site.

> This file is **instance-owned** (\`merge=ours\` in \`.gitattributes\`): framework
> upgrades never overwrite it. Edit it freely to describe your instance.

## Quick start

\`\`\`sh
npm ci --force && uv sync   # install the site + the editorial tooling
npm run dev                 # http://localhost:4321
npm run build               # production build + contract checks
\`\`\`

Requires Node.js ≥ 22.12 and [uv](https://docs.astral.sh/uv/) (which fetches
Python ≥ 3.12 for the editorial tooling).

## Where things live

- **\`place.config.ts\`** — this instance's identity (name, categories, map, links,
  home-page copy). The one file to edit to re-place the site.
- **\`knowledge/{Category}/*.md\`** — the content, and the single source of truth.
  Everything the site renders is derived from it at build time.
- **\`docs/playbook/\`** — the editorial canon (voice, structure, the quality bar).
- **\`public/media/\`** — images and other assets.

## Contributing

Content lives in \`knowledge/\`; never edit the derived, gitignored \`src/content/\`.
Run \`npm run build\` before pushing — CI runs the same gates. Framework internals
(\`src/\`, \`scripts/\`) come from [sekai-kb](https://github.com/wilsonkichoi/sekai-kb);
customize through config and content, and send framework changes upstream there.
`;
}

const DENYLIST_LOCAL_HEADER = `# genericity-denylist.local.txt — INSTANCE-OWNED additions to the genericity
# gate. Written by \`npm run init\` with this instance's place name; add more
# terms freely (one per line, case-insensitive substring match). Read
# additively by scripts/ci/check-genericity.sh alongside the framework
# denylist, which stays framework-owned so upgrades never conflict.
`;

/** Denylist terms for a place name: the full name plus its no-space form. */
export function denylistTerms(name) {
  const full = name.toLowerCase().trim();
  const collapsed = full.replace(/\s+/g, '');
  return [...new Set([full, collapsed])].filter(Boolean);
}

/* ── The write pass ──────────────────────────────────────────────────────── */

/**
 * Writes all adoption artifacts under `root`. Returns a log of actions taken
 * (one string per artifact) for the transcript.
 */
export function writeInstance(root, cfg) {
  const actions = [];
  const write = (rel, content) => {
    writeFileSync(join(root, rel), content);
    actions.push(`wrote   ${rel}`);
  };

  // place.config.ts — the single writer.
  write('place.config.ts', renderPlaceConfig(cfg));

  // knowledge/: remove demo content, reseed category dirs + INBOX.md.
  rmSync(join(root, 'knowledge'), { recursive: true, force: true });
  for (const cat of cfg.categories) {
    const dir = join(root, 'knowledge', cat.title);
    mkdirSync(dir, { recursive: true });
    writeFileSync(join(dir, '.gitkeep'), '');
  }
  actions.push(
    `seeded  knowledge/{${cfg.categories.map((c) => c.title).join(',')}}/`,
  );
  write('knowledge/INBOX.md', INBOX_MD);

  // CNAME: custom domain only. GitHub Pages default domains must not have one.
  const cname = join(root, 'CNAME');
  if (cfg.place.domain.toLowerCase().endsWith('.github.io')) {
    if (existsSync(cname)) {
      unlinkSync(cname);
      actions.push('removed CNAME (*.github.io domain)');
    } else {
      actions.push('skipped CNAME (*.github.io domain)');
    }
  } else {
    write('CNAME', `${cfg.place.domain}\n`);
  }

  // CLAUDE.md instance header block.
  write('CLAUDE.md', renderClaudeMd(cfg));

  // README.md: the instance repo front page (replaces the template's README).
  write('README.md', renderReadme(cfg));

  // FRAMEWORK-VERSION: the framework version this instance adopted. Written
  // `v`-prefixed to match the release-tag form (sekai-kb-vX.Y.Z) that the
  // /upgrade skill records, so wizard-written and upgrade-written values agree.
  const pkg = JSON.parse(readFileSync(join(root, 'package.json'), 'utf8'));
  write('FRAMEWORK-VERSION', `v${pkg.version}\n`);

  // Local genericity denylist: create or append (idempotent per term). The
  // framework denylist file is never touched.
  const localRel = 'scripts/ci/genericity-denylist.local.txt';
  const localPath = join(root, localRel);
  const existing = existsSync(localPath) ? readFileSync(localPath, 'utf8') : null;
  const have = new Set(
    (existing ?? '')
      .split('\n')
      .map((l) => l.trim())
      .filter((l) => l && !l.startsWith('#')),
  );
  const missing = denylistTerms(cfg.place.name).filter((t) => !have.has(t));
  if (existing === null) {
    write(localRel, `${DENYLIST_LOCAL_HEADER}${missing.join('\n')}\n`);
  } else if (missing.length > 0) {
    const sep = existing.endsWith('\n') ? '' : '\n';
    writeFileSync(localPath, `${existing}${sep}${missing.join('\n')}\n`);
    actions.push(`appended ${localRel} (+${missing.length} term(s))`);
  } else {
    actions.push(`kept    ${localRel} (terms already present)`);
  }

  // Template → instance: drop the marker so the gates scan code trees only.
  const marker = join(root, '.sekai-template');
  if (existsSync(marker)) {
    unlinkSync(marker);
    actions.push('removed .sekai-template (instance mode)');
  }

  // Dev-plugin strip: the framework's own dev-workflow state (config + engineering
  // rules under .agent-toolkit/, and the reference line that points at it) is
  // framework-development state, never adopter content. A fresh instance ships zero
  // dev-plugin state; an adopter who wants the dev workflow runs `dev:setup` to
  // create their own. Strip the tree and the AGENTS.md reference block here;
  // check-init.sh asserts both are absent post-init.
  const agentToolkit = join(root, '.agent-toolkit');
  if (existsSync(agentToolkit)) {
    rmSync(agentToolkit, { recursive: true, force: true });
    actions.push('removed .agent-toolkit/ (dev-plugin state not shipped to adopters)');
  }
  // AGENTS.md is instance-owned but seeded from the framework starter; remove only
  // the sentinel-delimited dev-plugin block, leaving the rest of the file intact.
  const agentsPath = join(root, 'AGENTS.md');
  if (existsSync(agentsPath)) {
    const before = readFileSync(agentsPath, 'utf8');
    const after = before.replace(
      /\n+<!-- dev-plugin:start[\s\S]*?dev-plugin:end -->[ \t]*\n?/,
      '\n',
    );
    if (after !== before) {
      writeFileSync(agentsPath, after);
      actions.push('stripped dev-plugin reference block from AGENTS.md');
    }
  }

  return actions;
}
